storage: /verdaccio/storage


auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: 100 

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@/':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

logs:
  - {type: stdout, format: pretty, level: http}
